name: Run GitHUB API Postman NewMan Collection Action
on:
  workflow_dispatch:
  
jobs:
  build:
    name: Creating Ubuntu Runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true

      - name: Install NewMan and HTMLextra reporter plugins
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          npm install -g newman-reporter-slackreporter
          npm install -g newman-reporter-allure

      - name: Create Test Results Folder
        run: mkdir -p GitHubAPITestResults

      - name: Get Current TimeStamp
        id: current_TimeStamp
        run: echo "current_TimeStamp=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Run the collection with Newman and HTMLextra
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL_RJD}}
          GIT_TOKEN: ${{secrets.TOKEN_ACCESS}}
        run: |
          newman run "Postman Collections/github_api_testing.json" -e "Postman Collections/GitTest.postman_environment.json" --env-var "[userTokenKey]=[$GIT_TOKEN]" -r htmlextra,slackreporter,allure --reporter-htmlextra-browserTitle "GitHub API Report" --reporter-htmlextra-title "GITHUB API Testing DashBoard" --reporter-htmlextra-export GitHubAPITestResults/postman-newman-report.html --reporter-slackreporter-webhookurl $SLACK_WEBHOOK_URL --reporter-allure-export GitHubAPITestResults/allure-postman-report 

      - name: Upload generated HTML file to Github Action
        uses: actions/upload-artifact@v3
        with: 
          name: GitHubAPITestingReport_${{env.current_TimeStamp}}
          path: GitHubAPITestResults
        

  
